In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1=[4,5,6,7,"sudh",34.565,True]

In [9]:
a1=np.array(l1)####its converting in string format

In [10]:
a2=np.array([[1,2,2],[4,5,6]])

In [11]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [13]:
a2

array([[1, 2, 2],
       [4, 5, 6]])

In [14]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
a1.ndim  ## ndim= give dimension

1

In [16]:
a2.ndim

2

In [18]:
a3.ndim

3

In [ ]:
## Size total number of elements

In [19]:
a1.size

7

In [20]:
a2.size

6

In [21]:
a3.size

9

In [ ]:
##shape

In [22]:
a1.shape

(7,)

In [23]:
a2.shape  ## 2 is row n 3 is column

(2, 3)

In [24]:
a3.shape  ## 3  cross 3 with 1 matrix in reverse x,y,z

(1, 3, 3)

In [27]:
np.random.randint(2,50,(2,3,4))

array([[[21, 41, 17, 25],
        [46, 20, 48, 26],
        [37, 20,  2,  8]],

       [[13, 43, 11, 33],
        [26, 26, 26, 44],
        [34, 11, 14, 37]]])

In [28]:
np.random.rand(2,3)

array([[0.78948061, 0.1732291 , 0.6443888 ],
       [0.0807863 , 0.12429009, 0.63376354]])

In [33]:
a4= np.random.randn(4,4)

In [30]:
##randin
##rand
##randn

In [31]:
## dataset which mean = 0 n normal standar deviation is 1 is call noramlization

In [34]:
a4

array([[-0.64766736, -0.35492169,  1.67646672,  1.0779016 ],
       [ 0.22132197,  0.03716085,  0.32278697, -1.02946979],
       [ 1.03050744, -0.42973803,  0.50275167, -0.0914357 ],
       [-0.13825963, -0.4537807 , -0.21141053, -0.38728305]])

In [35]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [36]:
a4.reshape(8,2)

array([[-0.64766736, -0.35492169],
       [ 1.67646672,  1.0779016 ],
       [ 0.22132197,  0.03716085],
       [ 0.32278697, -1.02946979],
       [ 1.03050744, -0.42973803],
       [ 0.50275167, -0.0914357 ],
       [-0.13825963, -0.4537807 ],
       [-0.21141053, -0.38728305]])

In [37]:
a4.reshape(16,1)

array([[-0.64766736],
       [-0.35492169],
       [ 1.67646672],
       [ 1.0779016 ],
       [ 0.22132197],
       [ 0.03716085],
       [ 0.32278697],
       [-1.02946979],
       [ 1.03050744],
       [-0.42973803],
       [ 0.50275167],
       [-0.0914357 ],
       [-0.13825963],
       [-0.4537807 ],
       [-0.21141053],
       [-0.38728305]])

In [38]:
a4.reshape(2,-1) ##negative number automatically reutrn the factorial

array([[-0.64766736, -0.35492169,  1.67646672,  1.0779016 ,  0.22132197,
         0.03716085,  0.32278697, -1.02946979],
       [ 1.03050744, -0.42973803,  0.50275167, -0.0914357 , -0.13825963,
        -0.4537807 , -0.21141053, -0.38728305]])

In [40]:
a4.reshape(2,2,4)

array([[[-0.64766736, -0.35492169,  1.67646672,  1.0779016 ],
        [ 0.22132197,  0.03716085,  0.32278697, -1.02946979]],

       [[ 1.03050744, -0.42973803,  0.50275167, -0.0914357 ],
        [-0.13825963, -0.4537807 , -0.21141053, -0.38728305]]])

In [41]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.64766736, -0.35492169,  1.67646672,
                 1.0779016 ],
               [ 0.22132197,  0.03716085,  0.32278697,
                -1.02946979]],

              [[ 1.03050744, -0.42973803,  0.50275167,
                -0.0914357 ],
               [-0.13825963, -0.4537807 , -0.21141053,
                -0.38728305]]]]]]]]]])

In [42]:
a1


array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [43]:
a1[0]

'4'

In [44]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [45]:
a1[2:6:2]


array(['6', 'sudh'], dtype='<U32')

In [46]:
a1[::-1] ##reverse 

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [47]:
a2

array([[1, 2, 2],
       [4, 5, 6]])

In [49]:
a2[0]

array([1, 2, 2])

In [51]:
a2[:,1:]

array([[2, 2],
       [5, 6]])

In [52]:
a2[:,[1,2]]

array([[2, 2],
       [5, 6]])

In [53]:
a2[[0,1],1:]

array([[2, 2],
       [5, 6]])

In [55]:
a2[[0,1],1:]

array([[2, 2],
       [5, 6]])

In [56]:
a5=np.random.randint(2,90,(6,5))

In [57]:
a5

array([[54, 55, 66,  9, 49],
       [46, 42, 56, 66, 57],
       [62, 42, 19, 70, 28],
       [14, 42, 35, 52, 29],
       [58, 51, 20, 17, 30],
       [ 8, 11, 37, 11,  5]])

In [58]:
a5[a5>40]

array([54, 55, 66, 49, 46, 42, 56, 66, 57, 62, 42, 70, 42, 52, 58, 51])

In [59]:
a5

array([[54, 55, 66,  9, 49],
       [46, 42, 56, 66, 57],
       [62, 42, 19, 70, 28],
       [14, 42, 35, 52, 29],
       [58, 51, 20, 17, 30],
       [ 8, 11, 37, 11,  5]])

In [64]:
a5[0,1]

55

In [65]:
a5[0,1]=100

In [66]:
a5

array([[ 54, 100,  66,   9,  49],
       [ 46,  42,  56,  66,  57],
       [ 62,  42,  19,  70,  28],
       [ 14,  42,  35,  52,  29],
       [ 58,  51,  20,  17,  30],
       [  8,  11,  37,  11,   5]])

In [71]:
a6=np.random.randint(0,3,(3,3))

In [68]:
a7=np.random.randint(0,3,(3,3))

In [72]:
a6

array([[1, 1, 0],
       [1, 2, 0],
       [0, 1, 2]])

In [70]:
a7

array([[2, 2, 1],
       [2, 0, 0],
       [0, 2, 1]])

In [73]:
a6*a7

array([[2, 2, 0],
       [2, 0, 0],
       [0, 2, 2]])

In [74]:
a6@a7 ## @ is for matrix multiplication

array([[4, 2, 1],
       [6, 2, 1],
       [2, 4, 2]])

In [75]:
a6

array([[1, 1, 0],
       [1, 2, 0],
       [0, 1, 2]])

In [76]:
a6+100

array([[101, 101, 100],
       [101, 102, 100],
       [100, 101, 102]])

In [77]:
a6*2

array([[2, 2, 0],
       [2, 4, 0],
       [0, 2, 4]])

In [78]:
a6/0

C:\Users\Ankita\AppData\Local\Temp\ipykernel_2300\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Ankita\AppData\Local\Temp\ipykernel_2300\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, nan],
       [inf, inf, nan],
       [nan, inf, inf]])

In [79]:
##inf symbol is available in numpy

In [80]:
a6

array([[1, 1, 0],
       [1, 2, 0],
       [0, 1, 2]])

In [81]:
a6**3 ## power operation

array([[1, 1, 0],
       [1, 8, 0],
       [0, 1, 8]], dtype=int32)

In [83]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
a9=np.ones((4,5))

In [86]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [87]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [88]:
a9 + np.array([1,2,3,4,5])  ## its called broadcasting operations

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [89]:
##operations columnwise

In [90]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [93]:
np.array([[1,2,3,4]]).T +a9 ## T transpose

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [97]:
a6


array([[1, 1, 0],
       [1, 2, 0],
       [0, 1, 2]])

In [98]:
a6.T

array([[1, 1, 0],
       [1, 2, 1],
       [0, 0, 2]])

In [99]:
a5

array([[ 54, 100,  66,   9,  49],
       [ 46,  42,  56,  66,  57],
       [ 62,  42,  19,  70,  28],
       [ 14,  42,  35,  52,  29],
       [ 58,  51,  20,  17,  30],
       [  8,  11,  37,  11,   5]])

In [100]:
np.sqrt(a5)##sqaureroot

array([[ 7.34846923, 10.        ,  8.1240384 ,  3.        ,  7.        ],
       [ 6.78232998,  6.4807407 ,  7.48331477,  8.1240384 ,  7.54983444],
       [ 7.87400787,  6.4807407 ,  4.35889894,  8.36660027,  5.29150262],
       [ 3.74165739,  6.4807407 ,  5.91607978,  7.21110255,  5.38516481],
       [ 7.61577311,  7.14142843,  4.47213595,  4.12310563,  5.47722558],
       [ 2.82842712,  3.31662479,  6.08276253,  3.31662479,  2.23606798]])

In [101]:
np.exp(a5)##expotential

array([[2.83075330e+23, 2.68811714e+43, 4.60718663e+28, 8.10308393e+03,
        1.90734657e+21],
       [9.49611942e+19, 1.73927494e+18, 2.09165950e+24, 4.60718663e+28,
        5.68572000e+24],
       [8.43835667e+26, 1.73927494e+18, 1.78482301e+08, 2.51543867e+30,
        1.44625706e+12],
       [1.20260428e+06, 1.73927494e+18, 1.58601345e+15, 3.83100800e+22,
        3.93133430e+12],
       [1.54553894e+25, 1.40934908e+22, 4.85165195e+08, 2.41549528e+07,
        1.06864746e+13],
       [2.98095799e+03, 5.98741417e+04, 1.17191424e+16, 5.98741417e+04,
        1.48413159e+02]])

In [102]:
np.log(a5) ## log 

array([[3.98898405, 4.60517019, 4.18965474, 2.19722458, 3.8918203 ],
       [3.8286414 , 3.73766962, 4.02535169, 4.18965474, 4.04305127],
       [4.12713439, 3.73766962, 2.94443898, 4.24849524, 3.33220451],
       [2.63905733, 3.73766962, 3.55534806, 3.95124372, 3.36729583],
       [4.06044301, 3.93182563, 2.99573227, 2.83321334, 3.40119738],
       [2.07944154, 2.39789527, 3.61091791, 2.39789527, 1.60943791]])

In [105]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [106]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [107]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.arange(1,10,2.5)##arange take float values n give  the outcome

array([1. , 3.5, 6. , 8.5])

In [109]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [110]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [111]:
np.linspace(2,3,num=50,retstep=True)##retstep step size

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [112]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [113]:
np.eye(5) ## 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
##Data visualisation

In [117]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [116]:
!pip install cufflinks

Defaulting to user installation because normal site-packages is not writeable
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=adf00189cf10aadba336c00a591cb6faec2374ad5382f2b979ce6c75db34cf45
  Stored in directory: c:\users\ankita\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [119]:
cf.go_offline()

In [120]:
np.random.randn(100,3)

array([[-6.51438736e-02,  1.93308789e-01,  1.98754065e-03],
       [ 2.98714532e-01, -6.20780262e-01,  2.56066181e+00],
       [-7.80477229e-01,  6.48633451e-01, -2.37290396e-02],
       [ 3.17063040e-01,  3.19484749e-01,  5.98581543e-01],
       [ 2.25074704e-01, -3.67748428e-01,  2.96268339e-01],
       [ 1.92405269e+00,  5.19492692e-01, -2.10684001e+00],
       [-4.03815421e-01,  2.42100434e-01, -2.23617145e+00],
       [-3.72086089e-01, -7.19688654e-01,  6.74806750e-01],
       [ 1.07691588e+00, -2.83560928e-01,  4.95786653e-01],
       [ 1.19394724e+00,  1.20677971e+00,  6.65391275e-01],
       [ 1.91161077e+00,  4.00399358e-01,  4.85763325e-01],
       [ 2.43316758e-02, -8.65362404e-01, -4.17455895e-02],
       [ 7.37039031e-01, -1.25662784e+00, -8.54926662e-01],
       [-1.67016714e+00, -9.06510245e-01, -7.72403942e-01],
       [ 1.05234504e+00,  7.61973457e-01, -2.67471640e-01],
       [ 2.81671593e-01,  7.09590250e-02, -1.78201696e+00],
       [ 1.77194990e+00, -1.19272121e+00

In [121]:
pd.DataFrame(np.random.randn(100,3))

0         1         2
0   0.162924  0.360727 -0.573046
1  -1.562819 -0.376421 -0.016288
2  -2.084935 -0.562584 -0.671951
3   0.649664  1.509551 -1.508675
4   1.041051  0.948317 -2.009664
..       ...       ...       ...
95  0.055996  0.598229  0.121850
96  0.568185 -1.087741 -0.415740
97  0.602029  0.902199  0.105131
98  1.388155 -2.552615 -1.599352
99 -0.850839  0.546556  0.888154

[100 rows x 3 columns]

In [126]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [125]:
df.iplot()

In [128]:
df1=pd.DataFrame(np.random.randint(3,100,(100,1)))

In [129]:
df1

0
0   49
1   72
2   93
3   47
4   24
..  ..
95  99
96  91
97  31
98  37
99  56

[100 rows x 1 columns]

In [130]:
df1.iplot()

In [131]:
df

A         B         C
0  -0.075723 -1.123906  0.649242
1  -2.138945  0.818861 -2.588794
2   0.549061 -1.148410 -0.075187
3   0.468404 -0.139532  0.347926
4  -0.416260 -0.552815 -0.533627
..       ...       ...       ...
95 -0.992737  1.193879 -0.296364
96  2.436495  1.269456  0.035458
97 -0.638981  0.376352  1.563568
98 -0.226681  0.431936  0.001555
99  0.355255  0.404977 -0.866197

[100 rows x 3 columns]

In [132]:
df.iplot(x='A',y='B',mode='markers')

In [134]:
df2=sns.load_dataset('titanic')

In [135]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [136]:
df2.iplot(x= 'age',y='fare',mode='markers')

In [137]:
df2.iplot(x= 'age',y='pclass',mode='markers')

In [138]:
df2.iplot(x= 'fare',y='pclass',mode='markers')

In [139]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [140]:
df2.iplot(kind='bar',x='sex',y= 'survived')